### ISSUE TITLE
最新版本启动需要的api及数据库

### ISSUE THREAD

**Issue by Pinkpiglet** [AstraSurge/gpteams#12]
1.0.0-beta 需要启用Cloud Firestore API及datastore才能正常启动
Cloud Firestore AP申请连接：https://console.developers.google.com/apis/api/firestore.googleapis.com/overview?project=填写messagingSenderId
Datastore 申请连接：https://console.cloud.google.com/datastore/setup?project=填写projectId

**Comment by suikodev** [comment]
wiki 已添加相关说明
