### ISSUE TITLE
登录页无法发送邮件及短信验证码。

### ISSUE THREAD

**Issue by Pinkpiglet** [AstraSurge/gpteams#15]
建议登录页面邮箱登录、手机号能够通过后端调用谷歌api，实现国内正常登录。

**Comment by suikodev** [comment]
1. 邮箱登录可以在后端调用
2. 手机号不可以

这两点有相关进展我会同步到这里。

**Comment by wangjueszu** [comment]
also waiting

**Comment by suikodev** [comment]
更新一下，因为 identitytoolkit.googleapis.com 被墙的原因，firebase auth 在中国大陆无法使用。实现后端调用 firebase API 后续也是无法使用的，因为前端还调用了 firebase auth 其他的一些方法。目前不打算在这个方向花时间。
