### ISSUE TITLE
关于退出登录后点击邮箱登录出现倒计时问题

### ISSUE THREAD

**Issue by Pinkpiglet** [AstraSurge/gpteams#18]
1、登录退出后，点击邮箱登录方式，出现发送倒计时，下面的图片是点击邮箱登录抓的。
![image](https://user-images.githubusercontent.com/38532706/228197292-e343fb9a-fd5d-4d68-b92b-b3678e2d0e31.png)

**Comment by suikodev** [comment]
在邮箱链接页面发起登录操作后会重置等待时间，有问题可以 reopen

**Comment by Pinkpiglet** [comment]
@suikodev 退出到登录页面点击邮箱登录，进去邮箱登录页面未点击发送邮件出现的。
