### ISSUE TITLE
原项目有个PR也做了管理系统，但是没有WEBUI

### ISSUE THREAD

**Issue by assassinliujie** [AstraSurge/gpteams#24]
https://github.com/Chanzhaoyu/chatgpt-web/pull/589
我想转换到这个管理系统，请问这个系统可以自己使用mongodb数据库吗还是说已经打包好了

**Comment by suikodev** [comment]
用的 firebase 服务里的 [firestore](https://firebase.google.com/docs/firestore?hl=zh-cn)

**Comment by suikodev** [comment]
如果你是想迁移的话，可以添加导入功能，如果你有比较好的想法的话，请移步到 #27 中讨论
