### ISSUE TITLE
前端加载时间长及管理账号配置建议

### ISSUE THREAD

**Issue by Pinkpiglet** [AstraSurge/gpteams#35]
1、前端这个链接请求超时，导致前端一致加载中，超时后才能进入登录页。
![image](https://user-images.githubusercontent.com/38532706/229334141-e51b4a8a-586a-4389-ba3c-e71f78502a0f.png)
2、建议将管理员账号配置进firestore中，方便管理。

**Comment by suikodev** [comment]
1. 这类问题暂时不优先解决
2. 暂时不会加
