### ISSUE TITLE
邮箱登录firebase免费版只能每天使用5次问题。

### ISSUE THREAD

**Issue by Pinkpiglet** [AstraSurge/gpteams#36]
1、目前邮箱登录免费次数过少，建议优化邮箱登录。

**Comment by suikodev** [comment]
已在[开发看板](https://sharing.clickup.com/31625481/b/h/6-900200430791-2/756b82376fc8197)上排期，下周一前会优化

**Comment by suikodev** [comment]
其实绑定信用卡就会有很高的免费使用额度了

**Comment by suikodev** [comment]
由于项目方向调整，目前不准备在 auth 上花更多的时间，抱歉。
