### ISSUE TITLE
VITE_APP_NAME variable does not work

### ISSUE THREAD

**Issue by Root-FTW** [AstraSurge/gpteams#43]
I added the variable VITE_APP_NAME in my railway, but it does not work, the name I assigned is not reflected in my deployment.

![2023_04_03_18_07_20](https://user-images.githubusercontent.com/108767514/229660203-f1ef0bf9-90a8-4730-932c-ae1327b9011e.png)

**Comment by suikodev** [comment]
I'll fix it later
