### ISSUE TITLE
Getting this error every time 

### ISSUE THREAD

**Issue by Urmi10799** [AstraSurge/gpteams#45]
Error message: You do not have permission to access this account. Please contact the administrator if you believe this is an error
which is referred to this: noPermissionToSignIn 

Can't sign-in with google, phone number or passwordless sign-in. Everytime throwing this error. Everything is setup well but still this error message.

**Comment by suikodev** [comment]
1. check your `ROOT_ACCOUNT` env
2. Can you take a look at this: https://github.com/AstraSurge/gpteams/discussions/42
