### ISSUE TITLE
带引号的环境变量可能在用docker 部署时产生错误 Environment variable with quotes could cause error when deploying using docker

### ISSUE THREAD

**Issue by simulacraliasing** [AstraSurge/gpteams#47]
按照示例里的env.list带引号填写环境变量部署docker会出问题，去掉之后就没问题了。（只是我自己的情况）
Fill environment variables with quotes in env.list following docker deployment example in wiki will cause some error and error were solved after removing these quotes.(only my own case)

**Comment by suikodev** [comment]
已更新 wiki，感谢你的贡献
