### ISSUE TITLE
WIKI中docker方式部署命令错误太多

### ISSUE THREAD

**Issue by assassinliujie** [AstraSurge/gpteams#52]
sudo docker run --name gpteams -d -p 3002:3002 --env-file env.list ghcr.io/astrasurge/gpteams:latest

**Comment by suikodev** [comment]
只看到镜像名字错了，已更新

**Comment by assassinliujie** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AstraSurge/gpteams"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月6日(星期四) 凌晨0:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AstraSurge/gpteams] WIKI中docker方式部署命令错误太多 (Issue #52)





 
只看到镜像名字错了，已更新
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.

端口映射应该也错了Message ID: ***@***.***&gt;
