### ISSUE TITLE
部署之后无论以什么方式登录都报错

### ISSUE THREAD

**Issue by assassinliujie** [AstraSurge/gpteams#53]
![image](https://user-images.githubusercontent.com/68693675/230137940-364ebd23-1b12-480b-976e-2aaa0af5471e.png)
邮箱
![image](https://user-images.githubusercontent.com/68693675/230137974-359d73e8-4290-4539-88e1-089ce325493f.png)
google
![image](https://user-images.githubusercontent.com/68693675/230138060-4df4cff7-cbb0-4bb7-98aa-ac0ad6748525.png)
验证码
请问可以帮帮我吗，无法定位错误原因，使用docker和railway部署均报错

**Comment by assassinliujie** [comment]
> 检查一下 firebase 配置

我是按照wiki中的一步步配的，firebase那边有日志吗

**Comment by suikodev** [comment]
google 登录是否表现为为弹出一个新的窗口就立刻关闭了

**Comment by assassinliujie** [comment]
> google 登录是否表现为弹出一个新的窗口就立刻关闭了

没有任何弹窗

**Comment by assassinliujie** [comment]
![image](https://user-images.githubusercontent.com/68693675/230140228-0b8cfcf6-2c7b-43d1-8166-7248185cf95c.png)
这是我的配置文件，请问这里应该没有问题吧？

**Comment by suikodev** [comment]
在 firebase Authentication 是否有配置自己的域名

**Comment by assassinliujie** [comment]
> 在 firebase Authentication 是否有配置自己的域名

![image](https://user-images.githubusercontent.com/68693675/230141186-88034be1-8c20-4eaa-b726-6bffdb16128d.png)
添加了

**Comment by assassinliujie** [comment]
> env.list 里面的环境变量不要带引号，已经更新 wiki

OK了，感谢

**Comment by suikodev** [comment]
如果还有部署相关的问题可以重开此 issue, 比较紧急的可以通过 telegram [联系我](https://t.me/suikodev)
