### ISSUE TITLE
您没有权限访问此账户。如果您认为这是一个错误，请联系管理员。

### ISSUE THREAD

**Issue by cjw-666** [AstraSurge/gpteams#59]
除了ROOT_ACCOUNT能够登录，其他账号提示“您没有权限访问此账户。如果您认为这是一个错误，请联系管理员。”
后台中账号都是启用中的

**Comment by suikodev** [comment]
如果没有设置白名单用户，则默认是只有 ROOT 账号可以登录的。
PS: 如果你想让所有人都能使用，可以在白名单中添加一个 . (英文句号)：
<img width="654" alt="image" src="https://user-images.githubusercontent.com/37903575/230778321-e9fa532f-c1a9-4400-8618-6b2b285a71db.png">
还有相关问题可以重开此 issue
