### ISSUE TITLE
本地测试可以登录，上传到服务器使用google登录显示   密钥无效 | Secret key is invalid，网址已授权。

### ISSUE THREAD

**Issue by Pinkpiglet** [AstraSurge/gpteams#6]
![image](https://user-images.githubusercontent.com/38532706/227458086-6d8d6e0c-c3d6-40fc-abf4-02b1ee104ab3.png)

**Comment by Pinkpiglet** [comment]
建议也添加上微软登录方式

**Comment by suikodev** [comment]
README 中关于部署的步骤还不是特别清晰，原因是准备在今天完成 vercel 部署方案后更新详细的逐步部署文档。

首先基于你**本地测试可以登录**的情况，我默认你的 firebase 的各种配置是没问题的。所以你的问题可能是因为在服务端没有配置登录账号限制，`AUTH_PHONE_REGEX` 与 `AUTH_EMAIL_REGEX` 这两个环境变量都没有设置。一定要至少设置其中之一。

**Comment by suikodev** [comment]
微软登录方式会加，但是会优先完成既定的功能，详见 README。

**Comment by Pinkpiglet** [comment]
@suikodev  AUTH_EMAIL_REGEX参数已经设置。
![image](https://user-images.githubusercontent.com/38532706/227474649-6a2b582f-6320-44f2-8e74-e4d9480b03aa.png)

**Comment by Pinkpiglet** [comment]
@Pinkpiglet 变量设置还是一样，提示Secret key is invalid

**Comment by suikodev** [comment]
你有 telegram 账号吗，可以用 telegram 联系我一下吗? 我的账号是 [@suikodev](https://t.me/suikodev) 我需要更具体的一些信息，但是这些信息我觉得放在 issue 里不太合适，比如你部署的地址，你 firebase 的一些配置等。

**Comment by Pinkpiglet** [comment]
@suikodev 最新版本谷歌邮箱已经可以登录。
